
package com.pruebacidenet.danielpineros.ws;

import javax.xml.ws.WebFault;

import com.pruebacidenet.danielpineros.esquema.EmpleadoException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebFault(name = "EmpleadoExceptionElement", targetNamespace = "http://com.pruebacidenet.danielpineros/esquema")
public class EmpleadoExceptionMessage extends Exception {

   /**
     * Esta clase fue generada por JAX-WS RI.
     * JAX-WS RI 2.2.11-b150616.1732
     * Versión fuente generada: 2.2
     *
   */
    private EmpleadoException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public EmpleadoExceptionMessage(String message, EmpleadoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmpleadoExceptionMessage(String message, EmpleadoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
      *
      * @devolver
      * devuelve el bean de error: com.pe.apps.schema.EmpleadoException
    */
    public EmpleadoException getFaultInfo() {
        return faultInfo;
    }

}
